schedules:
- cron: "5 4 * * 0"
  displayName: Weekly
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

# add agent_pool variable
variables:
- name: agent_pool
  value: "Azure Pipelines"
- name: create_release
  value: false

jobs:
- template: image-generation.yml
  parameters:
    image_type: ubuntu2204
    image_readme_name: Ubuntu2204-Readme.md
    image_template_name: ubuntu-22.04.pkr.hcl
    agent_pool: ${{ variables.agent_pool }}
    create_release: ${{ variables.create_release }}
