schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

# add agent_pool variable
variables:
- name: agent_pool
  value: "Azure Pipelines"
- name: create_release
  value: false

jobs:
- template: image-generation.yml
  parameters:
    image_type: windows2022
    image_readme_name: Windows2022-Readme.md
    image_template_name: windows-2022.pkr.hcl
    agent_pool: ${{ variables.agent_pool }}
    create_release: ${{ variables.create_release }}

